[package]
name = "uid"
version = "0.1.0"
edition = "2021"

[dependencies]
fast32 = "1.0.3"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v7", "serde"] }
