error_on_line_overflow = false
error_on_unformatted = false
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
style_edition = "2024"
wrap_comments = true
